### ISSUE TITLE
Accept pull request

### ISSUE THREAD

**Issue by JoabMendes** [IFRN/gosu-exemplos#3]
Olá @lrlucena, 
Eu fiz um [pull request](https://github.com/IFRN/gosu-exemplos/pull/2) adicionando o jogo que fiz em 20131 com Jorgiano. Tenho outros amigos que fizeram também e vou falar com eles para atualizarem. Se puder me adiconar na organização do [IFRN](https://github.com/IFRN) eu também agradeço. Tenho uns projetos interessantes que posso deixar lá como open source.

**Comment by lrlucena** [comment]
Olá Joab,

Coloquei você no grupo do administrador. Seria muito bom ter outros projetos também.

No caso dos exemplos de Ruby eu estava pensando em incluir os projetos como links para os projetos individuais. Colocar tudo em um projeto só está tornando o arquivo de download muito grande. Só não não como criar os links. Já vi isso em outro projetos (veja https://github.com/UNIVALI-L2S/Portugol/tree/master/Projetos)

**Comment by felipemfp** [comment]
@lrlucena,

Adicionei os projetos como submódulo (#4), assim o arquivo para download não fica muito grande. Infelizmente, não achei o repositório de _Crazy Crash_.
